/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.sridharan.sample;

public class Library {
    public boolean someLibraryMethod() {

        Object x = null;
        x.hashCode();
        return true;
    }
}
