/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.sridharan.sample;

import org.jspecify.annotations.Nullable;

public class Library {
    public boolean someLibraryMethod() {

        Object x = null;
        return x.hashCode() == 0;
    }

    static class Foo<T extends @Nullable Object> {
        Foo(T t) {}
        static <U extends @Nullable Object> Foo<U> create(U u, Foo<U> other) {
            return new Foo<>(u);
        }

//        static void test(Foo<@Nullable Object> f1, Foo<Object> f2) {
//            // no error expected
//            Foo<@Nullable Object> result = Foo.create(null, f1);
//            // error expected
//            Foo<@Nullable Object> result2 = Foo.create(null, f2);
//        }
    }
//
//    public Object foo() {
//        Object x = new Object();
//        if (x != null) {
//            return x;
//        }
//        return null;
//    }
}
